[package]
name = "questicon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.0.0"

[dependencies.mongodb]
version = "2.0.0"
default-features = false
features = ["tokio-runtime""]